### ISSUE TITLE
How to get fixtures from conftest.py

### ISSUE THREAD

**Issue by stuaxo** [chmp/ipytest#101]
I tried using this with a django project, and things seem OK, except the fixtures in my (django) project are not picked up - any idea how I can get those to work ?

EDIT:  The fixtures are in conftest.py in the project root and other places that have unit tests, when I run pytest manually these are picked up.

**Comment by chmp** [comment]
Hi @stuaxo 

thanks for the report. For simple fixtures discovery from `conftest.py` files seem to work out of the box. I added some test [here](https://github.com/chmp/ipytest/pull/102).

Do you have more information on the directory layout or an example you can share?

**Comment by chmp** [comment]
I will close this issue, as I can't reproduce it. Feel free to re-open.
