### ISSUE TITLE
%%ipytest input cells are mangled in .py conversion

### ISSUE THREAD

**Issue by westurner** [chmp/ipytest#116]
When I `nbconvert example.ipynb --to python` or a notebook, input cells prefixed with the %%ipytest line magic are disadvantageously mangled.

Given these input cells:

```py
%pip install -q ipytest
import ipytest
ipytest.autoconfig()
```

```python
%%ipytest
def test_1():
    assert False
```

This is the output for cell 2 from `nbconvert --to python` and JupyterLab `Save and Export Notebook As > Executable Script`:

```python
# In[2]


get_ipython().run_cell_magic('ipytest', '', 'import datetime\ndef test_1():\n    assert False\n')

```

This is the output from Google Colab `Download > Download .py`:

```python
# Commented out IPython magic to ensure Python compatibility.
# %%ipytest
# def test_1():
#    assert False
```

IMHO It would be better to just comment out `%%ipytest` when converting to `.py`, but I'm not sure if that's possible in IPython for specific cell magics yet or not:

```py
## %%ipytest 
def test_1():
    assert False
```

References:
- https://github.com/search?q=repo%3Ajupyter%2Fnbconvert%20magic&type=code
  - https://github.com/jupyter/nbconvert/blob/main/nbconvert/exporters/templateexporter.py#L51
  - https://github.com/jupyter/nbconvert/blob/main/nbconvert/exporters/script.py
    - https://github.com/jupyter/nbconvert/blob/main/share/templates/script/script.j2
  - https://github.com/jupyter/nbconvert/blob/main/nbconvert/exporters/python.py
    - https://github.com/jupyter/nbconvert/blob/main/share/templates/python/index.py.j2
      - `| ipython2ipython`
  - https://github.com/jupyter/nbconvert/blob/main/docs/source/api/preprocessors.rst
    - https://nbconvert.readthedocs.io/en/latest/api/preprocessors.html
  - `HighlightMagicsPreprocessor`
    - https://github.com/jupyter/nbconvert/blob/main/nbconvert/preprocessors/highlightmagics.py
    - https://github.com/jupyter/nbconvert/blob/71fde294f623083f364bf68e14f07459dee952e6/nbconvert/exporters/exporter.py#L96
- https://githu.com/search?q=repo%3Ajupyter%2Fnbconvert%20get_ipython&type=code
  - https://github.com/jupyter/nbconvert/issues/503#issuecomment-270524472
- `ipython2ipython`
  https://github.com/jupyter/nbconvert/blob/main/nbconvert/filters/strings.py#L220
  - `IPython.core.inputtransformer2:cell_magic`:
    https://github.com/ipython/ipython/blob/main/IPython/core/inputtransformer2.py#L121-L130

**Comment by westurner** [comment]
Possible solutions:
- Add a `%%% cell magicz` to IPython that just gets commented out upon conversion to Python script, per new spec
- Preprocess everything like HighlightMagicsPreprocessor and just comment out `%%ipytest`
  - This can be done with a RegexPreprocessor
- Modify the `cell_magic` function to special case `%%ipytest` for all
- Modify the `cell_magic` function to do lookup from a registry that installed cell magics would register to in order to define the behavior in the Python exporter just
- @carreau how to write pytest tests in a notebook and run them with a normal pytest runner if converted to python?

**Comment by westurner** [comment]
Additional solutions:
- - `pip install jupytext`
  - restart the notebook
  - File > Jupytext > Pair notebook with Nomarker format
  - File > Save (Ctrl-S, Ctrl-Shift-C s Enter)
  https://jupytext.readthedocs.io/en/latest/formats-scripts.html#the-nomarker-format
- `nbconvert --help`:
  ```
  [...]
  --config=<Unicode>
      Full path of a config file.
      Default: ''
      Equivalent to: [--JupyterApp.config_file]
  --to=<Unicode>
      The export format to be used, either one of the built-in formats
              ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']
              or a dotted object name that represents the import path for an
              ``Exporter`` class
      Default: ''
      Equivalent to: [--NbConvertApp.export_format]
  --template=<Unicode>
      Name of the template to use
      Default: ''
      Equivalent to: [--TemplateExporter.template_name]
  --template-file=<Unicode>
      Name of the template file to use
      Default: None
      Equivalent to: [--TemplateExporter.template_file]
  ```
  - specify a custom Exporter class that does what Jupytext Nomarker format does
  - specify a custom --template for --to python that does not run the `|ipython2ipython` filter

**Comment by chmp** [comment]
@westurner as this issue is not unique to `ipytest`, nor something that can be fixed in `ipytest`, I will it. Please raise the issue at the `nbconvert` repo or your conversion tool of choice.
