### ISSUE TITLE
ipytest doesn't seem to work with Python 2.7

### ISSUE THREAD

**Issue by pmgrafe** [chmp/ipytest#16]
In PyPI, this package is listed as supporting Python 2, but when I pip install it with Python 2.7 and run "import ipytest", I get the following error:

  File "lib\site-packages\ipytest\_util.py", line 73
    print(message, file=sys.stderr)
                       ^
SyntaxError: invalid syntax

Not sure it makes sense to actually bother fixing this since Python 2.7 support will be ending in the near future, but it might make sense to officially remove support.

**Comment by chmp** [comment]
Good catch. I will officially remove support. Since it did not seem to be an issue up to now.

**Comment by chmp** [comment]
I pushed a new version and officially removed pyhton 2 support. Thanks for the info.
