### ISSUE TITLE
Cleaning tests does not affect to test classes named as Test*

### ISSUE THREAD

**Issue by jerry-git** [chmp/ipytest#3]
If I have something like this:

cell 1
```python
class TestClass:
    def test_1(self):
        pass
```
cell 2
```
%%run_pytest[clean] '-v'

def test_2():
    pass
```

Running these in order will execute both `test_1` and `test_2`. I'd expect that only `test_2` is executed. I guess this originates from here: https://github.com/chmp/ipytest/blob/master/ipytest/__init__.py#L60

**Comment by jerry-git** [comment]
Easy fix for this would be to make the pattern checking case insensitive. Other possible options: make the pattern configurable (e.g. an argument to the cell magic) or maybe even dig the required information from `pytest` configuration. Anyway, let me know if you have any preferences, I can provide a PR for this.

**Comment by jerry-git** [comment]
Workaround for this seems to be to make `ipytest.clean_tests('Test*')` call between cells 1 & 2. However, as I am writing teaching/learning materials, I'd like to minimise the required boilerplate. Thus, I think it'd be nice to achieve the same behaviour as part of `run_pytest[clean]` cell magic.

**Comment by chmp** [comment]
Thanks for raising this issue. It completely slipped my radar. I like both your suggestions, exposing a way to configure the pattern and updating the default pattern. However, I would prefer to stick to updating the default pattern for now to not make the code more complex. 

I'll update the pattern to read `[Tt]est*`. That should match pytest's [behavior](https://docs.pytest.org/en/latest/reference.html#confval-python_classes).

**Comment by chmp** [comment]
I just pushed the changes and updated the package on PyPI. After running `pip install -U ipytest` your issue should be resolved.

**Comment by jerry-git** [comment]
Works like a charm. Thanks @chmp!
