### ISSUE TITLE
Upload sdists

### ISSUE THREAD

**Issue by xhochy** [chmp/ipytest#33]
We build the conda-forge packages for Python of `sdist` files, our auto-update bot is failing as the latest release only has a wheel.

**Comment by chmp** [comment]
And here I was wondering, who is uploading conda packages behind my back ;) 

Are there any specific requirements or can I just use `setup.py sdist --formats=zip`? If you have a python-only example I can copy from, I would be happy for pointers.

(Just as an FWI: all releases where wheel only. So I guess the conda-forge process changed)

**Comment by xhochy** [comment]
`setup.py sdist` (which produces a `tar.gz`) is preferrable.

> (Just as an FWI: all releases where wheel only. So I guess the conda-forge process changed)

No, the conda-forge recipe was a hacky workaround to use the wheel. But this doesn't work together with our automation machinery.

**Comment by chmp** [comment]
I uploaded an sdist for 0.8.0. Is the conda packaging is fixed by that? 

Then I will also add a proper upload script.

**Comment by xhochy** [comment]
Thanks!
