### ISSUE TITLE
Errors while running the example notebook

### ISSUE THREAD

**Issue by nvankayalapati** [chmp/ipytest#38]
I get the following error when I run the example notebook

`==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
../../.conda/envs/regression_env/lib/python3.7/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../.conda/envs/regression_env/lib/python3.7/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../.conda/envs/regression_env/lib/python3.7/site-packages/pluggy/manager.py:87: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
../../.conda/envs/regression_env/lib/python3.7/site-packages/ipytest/_pytest_support.py:143: in pytest_collect_file
    parent, fspath=path.new(ext=".py"), module=self.module
../../.conda/envs/regression_env/lib/python3.7/site-packages/ipytest/_pytest_support.py:156: in from_parent
    self = super().from_parent(parent, fspath=fspath)
E   AttributeError: 'super' object has no attribute 'from_parent'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!`

![image](https://user-images.githubusercontent.com/26265805/79336830-095ed380-7f42-11ea-877a-09e43651d6b7.png)

**Comment by chmp** [comment]
The most recent version of ipytest, requires `pytest>=5.0.0`. Could it be that your pytest version is out of date? Try upgrading pytest with `pip install -U pytest`.

**Comment by nvankayalapati** [comment]
Yes, that was it. I was using pytest< 5.0.0. Thank you for your super quick response. Also, I sincerely thank you for your package.

**Comment by chmp** [comment]
Thanks for the feedback :). 

Re. the issue: Maybe I should just make pytest finally a proper requirement with proper version number.
