### ISSUE TITLE
Added ipytest to awesome-jupyter

### ISSUE THREAD

**Issue by markusschanta** [chmp/ipytest#4]
Hi @chmp,

JFYI, I added ipytest to [awesome-jupyter](https://github.com/markusschanta/awesome-jupyter).

Cool project! In particular, anything that makes converting notebook code to proper tests is awesome! 

Cheers,
Markus

**Comment by chmp** [comment]
Thanks for the kind feedback. Your list also looks really cool, I already saw some interesting things to try out.

**Comment by markusschanta** [comment]
Thank you too! It's not just my work but the collaborative product of the people who contributed to it. In that spirit, if you can think of anything that should go on there, feel free to create a PR! 😊

**Comment by chmp** [comment]
Will do :).
