### ISSUE TITLE
Latest release has an undeclared IPython depencency

### ISSUE THREAD

**Issue by xhochy** [chmp/ipytest#43]
See the failing CI in the conda recipe: https://github.com/conda-forge/ipytest-feedstock/pull/2

Either this should be lazily imported or `ipython` should be listed in the `setup.py`.

**Comment by chmp** [comment]
Thanks for the report :). I kinda knew that playing fast and loose with my dependencies is probably not a overly great idea, but it has been causing quite a lot of trouble in the last weeks.

**Comment by chmp** [comment]
I pushed a new 0.9.1 release with ipython as dependency

**Comment by chmp** [comment]
Damn. Saw the next failed test. I guess pytest finally removed py.* as a depedency

**Comment by chmp** [comment]
@xhochy not sure what goes wrong. Pytest still declares py as a depedency, I in turn depend on pytest. AFAIK, installing ipytest should install both pytest and py. No idea what the pipeline fails:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=183876&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=c09a5a47-eec3-5700-9284-6f1bd7b23501&l=564

**Comment by xhochy** [comment]
The correct dependencies were missing from the recipe, all fine now.

**Comment by chmp** [comment]
Perfect. Thanks :)
