### ISSUE TITLE
UsageError: Line magic function `%%run_pytest` not found.

### ISSUE THREAD

**Issue by highpost** [chmp/ipytest#44]
I installed ipytest with pip in my virtualenv and then created a Jupyter notebook with Visual Studio Code:
```
import ipytest
ipytest.autoconfig()

%%run_pytest[clean] -qq 

def test_example():
    assert [1, 2, 3] == [1, 2, 3]
```
But I'm getting an error that the magic function isn't being found:
```
UsageError: Line magic function `%%run_pytest` not found.
```
Notes:

- The run_pytest cell magic is visible in the list returned by %lsmagic.
- I get the same error when I use ipython.

**Comment by chmp** [comment]
Hi @highpost . Thanks for the report. Just checking: you are using two separate cells for the ipytest setup and then the test itself, right? It should look like:

![grafik](https://user-images.githubusercontent.com/949987/88163231-a18be900-cc12-11ea-9af5-743dc28fa6ee.png)

I just re-read the Readme and have to admit, that this part is not quite clearly formulated. I will update it.

**Comment by highpost** [comment]
Yes, that works. My mistake was combining them into a single cell.
