### ISSUE TITLE
warning when running tests if have "import dash" run beforehand

### ISSUE THREAD

**Issue by yuuuxt** [chmp/ipytest#48]
If I run `import dash` before running any tests, the following warning will appear:
`PytestAssertRewriteWarning: Module already imported so cannot be rewritten: dash`

I assume this is enough to reproduce this issue. Feel free to contact if you need more information :)

**Comment by chmp** [comment]
Thanks for the report @yuuuxt . You're right, I should be able to reproduce this issue :).  TBH. I'm quite swamped at the moment. I'll will not have time to look at this issues until in about two weeks.

**Comment by chmp** [comment]
Since ipytest rewrites the assertions of the notebook independently from pytest, you can safely disable global global assertion rewriting:

```python
import ipytest
ipytest.autoconfig(addopts=['-q', '--assert=plain'])
```

This should solve the warning. Could you give it a try and see whether anything else breaks? Thanks :)

**Comment by yuuuxt** [comment]
I tried with a simple test case and it works fine. However, I may not encounter more complex cases.

Thanks for solving this! :)

**Comment by chmp** [comment]
Thanks for the feedback. Feel free to re-open if the issue pops up again.

**Comment by astrojuanlu** [comment]
Too bad that with this configuration the fancy coloring is gone, would be cool to find an alternative solution.
