### ISSUE TITLE
Get TypeError upon (otherwise successful) use of pytest.mark.parametrize

### ISSUE THREAD

**Issue by munichpavel** [chmp/ipytest#51]
May be related to #39

I can run tests using `pytest.mark.parametrize`, but jupyter gives me a `TypeError`:

```python
%%run_pytest[clean]


@pytest.mark.parametrize(
    'text,last_text_to_exclude,expected',
    [
        (
            '''Dear colleagues, thank you for taking the time to respond to this short survey. \n
            Thank you very much! - Ranks - Topics of the highest priority & interest - 
            Storage & Querying (Prepare) - Rank''',
            'Topics of the highest priority & interest - ', 'Storage & Querying (Prepare) - Rank'
        )
    ]
)
def test_extract_text_after(text, last_text_to_exclude, expected):
    text = (
        'Dear colleagues, thank you for taking the time to respond to this short survey. \n'
        'Thank you very much! - Ranks - Topics of the highest priority & interest - '
        'Storage & Querying (Prepare) - Rank'
    )
    last_text_to_exclude = 'Topics of the highest priority & interest - '
    res = extract_text_after(text, last_text_to_exclude)
    expected = 'Storage & Querying (Prepare) - Rank'
    assert res == expected
    
try:
    test_extract_text_after()
except TypeError as err:
    print(err)
```

Cell output
```console
test_extract_text_after() missing 3 required positional arguments: 'text', 'last_text_to_exclude', and 'expected'
.                                                                                                                               [100%]
1 passed in 0.01s
```

Here are some possibly relevant version of my python environment:

```console
ipykernel==5.5.0
ipytest==0.9.1
ipython==7.20.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
...
jupyter==1.0.0
jupyter-client==6.1.11
jupyter-console==6.2.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
...
pytest==6.2.2
```

with python Python 3.8.3

**Comment by chmp** [comment]
Hey Paul.  I have a little trouble following your example. If the error comes from this part:

```
try:
    test_extract_text_after()
except TypeError as err:
    print(err)
```

That's to be expected. The test function are called by pytest, which makes sure the correct fixture values are passed. Making sure that pytest knows about your code and is able to call it is exactly the functionality that ipytest provides. Outside of the pytest runtime, `test_extract_text_after` should behave like any other python function, i.e., you would need to pass three arguments or get a TypeError in your case.

**Comment by munichpavel** [comment]
Of course, I forgot to drop the sans ipytest running of the test, i.e. without ipytest I would define a test with no arguments, and then run it in a cell, which would raise an assertion error if the test fails, but in my case a type error because I parametrized the test.

With the actual ipytest usage (no extra call of test function), everything is fine. Thank you!
