### ISSUE TITLE
Add breakpoint() support

### ISSUE THREAD

**Issue by alac1984** [chmp/ipytest#80]
It would be very interesting that, besides using `--pbd` option in autoconfig, we have `breakpoint()` support too.

I use breakpoints a lot with pytest when I'm developing new methods and functions, and I miss them in this library.

**Comment by chmp** [comment]
It seems that this is a [bug in IPython](https://github.com/ipython/ipykernel/issues/897). So there is not much I can do about it. As [the original breakpoint hook stills seems to work](https://github.com/jupyterlab/jupyterlab/issues/10996#issuecomment-911928272). You could try resetting it in your notebook:

```python
import sys
sys.breakpointhook = sys.__breakpointhook__
```

For me this fixed the issue.

**Comment by chmp** [comment]
Closing this for now, as this issue seems to be an upstream one.
