### ISSUE TITLE
Fix conda-forge package

### ISSUE THREAD

**Issue by xhochy** [chmp/ipytest#98]
This seems to have vanished through the switch to `poetry`. One option could be to explicitly name it `LICENSE` as this is picked up automatically. I have not found an option on how to include a differently named license file (no poetry experience on my side).

**Comment by xhochy** [comment]
This is looking good.

**Comment by chmp** [comment]
I see the build is still failing with the error, that poetry could not be found: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=708247&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=639 

That's probably something to fix on your end, isn't it?

**Comment by xhochy** [comment]
Everything is fixed, thanks!

**Comment by chmp** [comment]
Thanks a lot of taking care of the conda-forge package!
